version: 2.1

restore-cache: &restore_cache
  restore_cache:
    keys:
      - npm-packages-{{ checksum "package-lock.json" }}

save-cache: &save_cache
  save_cache:
    key: npm-packages-{{ checksum "package-lock.json" }}
    paths:
      - ~/.cache/npm

fast-checkout: &fast-checkout
  attach_workspace:
    at: /home/circleci

filter-publishable: &filter-publishable
  tags: 
    only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
  branches:
    only: /main/

executors: 
  node:
    docker:
      - image: circleci/node
      - image: circleci/mongo
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin

jobs:
  checkout:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - run:
          name: "Install deps"
          command: npm ci
      - <<: *save_cache
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
            - project/node_modules
  run-integration-tests:
    executor: node
    steps:
      - <<: *fast-checkout
      - run:
          name: "run-integration-tests"
          command: npm run test:integration
  publish-to-npm:
    executor: node
    steps:
      - <<: *fast-checkout
      - run: 
          name: "Build Mongoose Repository"
          command: npm run build
      - run:
          name: "Authenticate on NPM registry"
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > /home/circleci/.npmrc
      - run:
          name: "Publish Package on NPM registry"
          command: npm publish

workflows:
  publish:
    jobs:
      - authorize-workflow:
          type: approval
      - checkout:
          requires:
            - authorize-workflow
      - run-integration-tests:
          name: run-integration-tests
          requires:
            - checkout
      - publish-to-npm:
          name: publish-to-npm
          requires: 
            - run-integration-tests
          filters:
            <<: *filter-publishable